# Generated by Django 4.1.2 on 2022-10-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusage',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
